### ISSUE TITLE
App still maintained?

### ISSUE THREAD

**Issue by IzzySoft** [MJonesDev/Ongoing-Notification-Reminder#3]
Does the "Old Project" prefix mean this app is no longer maintained? Or will there be further development and future releases?

**Comment by PanHyridae** [comment]
Correct, the Old Project tag means that this app is no longer maintained and there will be no further development. However, I did not archive it just in case anyone wants to still fork the code and use it for themselves.

**Comment by IzzySoft** [comment]
Thanks for the answer – and good luck with your current projects then!
